language: go
before_install:
- REPO_NAME=$(basename $PWD)
- GITHUB_PATH=$(dirname $(dirname $PWD))
- SYMANTEC_PROJECT_DIR=${GITHUB_PATH}/Symantec/${REPO_NAME}
- mkdir -p ${SYMANTEC_PROJECT_DIR}
- rsync -az ${TRAVIS_BUILD_DIR}/ ${SYMANTEC_PROJECT_DIR}/
- export TRAVIS_BUILD_DIR=${SYMANTEC_PROJECT_DIR}
- cd ${SYMANTEC_PROJECT_DIR}
- go get ./...

script: make all test
