#! /bin/bash --posix

set -e
set -o nounset

# Configuration. Quick and dirty for now.
readonly scratch_dir='/scratch'

# Pull in from the command line.
readonly type="$1"
readonly destination_raw="$2"

if [ "$type" != "s3" ]; then
    echo "Unknown type"
    exit 1
fi

# Introspect.
readonly document_url='http://169.254.169.254/latest/dynamic/instance-identity/document'
readonly document="$(wget -q -O - "$document_url")"
readonly account_id="$(echo "$document" | fgrep 'accountId' | cut -d'"' -f 4)"
readonly region="$(echo "$document" | fgrep 'region' | cut -d'"' -f 4)"

readonly destination="$(eval echo "$destination_raw")"

# Load secrets (API keys). The following variables should be set:
#   access_key_id
#   cert_file
#   key_file
#   secret_access_key
. "$scratch_dir/secrets"

readonly tmpdir="$(mktemp -d "$scratch_dir/$(basename "$0").XXXXXX")" || exit
trap "rm -rf $tmpdir" EXIT

cat > "$tmpdir/image"
ec2-bundle-image -c "$cert_file" -k "$key_file" -u "$account_id" \
  --image "$tmpdir/image" -d "$tmpdir" -r x86_64 --prefix image
ec2-upload-bundle -b "$destination" -m "$tmpdir/image.manifest.xml" \
  -a "$access_key_id" -s "$secret_access_key" --batch --retry
