#! /bin/bash --posix

set -o nounset
cd /

readonly boot_device="$1"

mount -n none -t proc "/proc"    || exit
mount -n none -t devtmpfs "/dev" || exit
mount -n none -t sysfs "/sys"    || exit

readonly root_uuid=$(blkid -o export "${boot_device}1" |\
			sed -nre 's/^UUID=(.*)$/\1/p')
echo "UUID=$root_uuid /  ext4  defaults  0 1" > /etc/fstab

# Reconfigure GRUB for new root file-system and install on boot device.
if [ -x /sbin/grub2-mkconfig ]; then
    grub2-mkconfig -o /boot/grub2/grub.cfg
    grub2-install "$boot_device"
elif [ -x /usr/sbin/grub-mkconfig ]; then
    grub-mkconfig -o /boot/grub/grub.cfg
    grub-install "$boot_device"
else
    if [ -r /boot/grub/grub.conf ]; then
	readonly grub_config_file='/boot/grub/grub.conf'
    else
	readonly grub_config_file='/boot/grub/grub.cfg'
    fi
    tmp="$(< "$grub_config_file")"
    echo "$tmp" | sed -r \
	-e "s/UUID=[^[:space:]]+/UUID=$root_uuid/g" \
	-e 's/quiet$/quiet console=ttyS0/' > "$grub_config_file"
    grub <<-EOF
	device (hd0) $boot_device
	root (hd0,0)
	setup (hd0)
EOF
fi

umount "/sys"
umount "/dev"
umount "/proc"
