#! /bin/bash --posix

case "$1" in
  start)
    cp -p /etc/fstab /mnt/etc
    chroot /mnt /make-bootable make-bootable
    rm /mnt/make-bootable
    exit 0
    ;;

  make-bootable)
    ;;

  *)
    echo "Usage: /etc/init.d/make-bootable {start|make-bootable}"
    exit 1
esac

mount -n none -t proc /proc
mount -n none -t devtmpfs /dev
mount -n none -t sysfs /sys

readonly boot_device=$(blkid -L rootfs | sed -re 's/([[:digit:]]+$)//')
readonly kernel_version=$(ls -v /lib/modules | tail -n 1)

# Build a new initramfs suited to the machine.
dracut --force "/boot/initramfs-$kernel_version.img" "$kernel_version"

# Reconfigure GRUB for new root file-system and install on boot device.
if [ -x /sbin/grub2-mkconfig ]; then
    grub2-mkconfig -o /boot/grub2/grub.cfg
    grub2-install "$boot_device"
else
    readonly grub_config_file='/boot/grub/grub.conf'
    tmp="$(< "$grub_config_file")"
    echo "$tmp" | sed -r \
	-e 's/UUID=[^[:space:]]+/LABEL=rootfs/g' \
	-e 's/quiet$/quiet console=ttyS0/' > "$grub_config_file"
    grub <<-EOF
	device (hd0) $boot_device
	root (hd0,0)
	setup (hd0)
EOF
fi
