#! /bin/bash --posix

set -eu

readonly command="$1"
shift

readonly bin="$GOPATH/bin/$command"
readonly target="/tmp/$LOGNAME/$command.tar.gz"

(cd $GOPATH/src; go install github.com/Symantec/Dominator/cmd/$command)

strip -o "$bin~" "$bin"
if cmp -s "$bin~" "$bin"; then
    rm "$bin~"
else
    touch -r "$bin" "$bin~"
    mv "$bin~" "$bin"
fi

readonly tmpdir="$(mktemp -d '/tmp/make-tarball.XXXXXX')" || exit
trap "rm -rf $tmpdir" EXIT

if [ -x "$PWD/cmd/$command/install" ]; then
    cp -p "$PWD/cmd/$command/install" "$tmpdir"
else
    cat > "$tmpdir/install" <<EOF
#! /bin/bash --posix

set -o nounset

cd "\${0%/*}"

. ./scripts/install.lib

install_all $command
EOF
    chmod a+rx "$tmpdir/install"
fi

tar --owner=0 --group=0 -czf $target \
    init.d/$command.* \
    scripts/install.lib \
    "$@" \
    -C $PWD/cmd/$command health-check.yml \
    -C "$tmpdir" install \
    -C $GOPATH bin/$command
