#! /bin/bash --posix

set -o nounset

cd "${0%/*}"

. ./scripts/install.lib

echo=

$echo mkdir -p /etc/ssl/image-unpacker || exit
$echo cp -p ssl/CA*.pem /etc/ssl || exit
$echo cp -p ssl/image-unpacker/*.pem /etc/ssl/image-unpacker || exit
$echo mkdir -p /usr/local/sbin || exit
$echo cp -p bin/* /usr/local/sbin || exit
$echo cp -p scripts/image-pusher/* /usr/local/etc || exit
install_service image-unpacker || exit
