#! /bin/bash --posix

set -o nounset

cd "${0%/*}"

. ./scripts/install.lib

echo=

$echo mkdir -p /etc/ssl/subd || exit
$echo cp -p ssl/CA.pem /etc/ssl || exit
$echo cp -p ssl/subd/cert.pem ssl/subd/key.pem /etc/ssl/subd || exit
$echo mkdir -p /usr/local/sbin || exit
$echo cp -p bin/* /usr/local/sbin || exit
install_service subd || exit
