#! /bin/bash --posix

set -ex

readonly dir='/tmp/dominator-unpack'

rm -rf "$dir" || true
mkdir -p "$dir"
wget -q -O /tmp/dominator.tar.gz http://mirror.symcpe.net/misc/Dominator/dominator.tar.gz
tar -C "$dir" -xzf /tmp/dominator.tar.gz
rm /tmp/dominator.tar.gz

"$dir/install"
rm -rf "$dir"

mkdir -p /var/lib/Dominator /var/log/dominator

chown -R dominator /etc/ssl/dominator /var/lib/Dominator /var/log/dominator

# Remove noise.
rm -f /etc/motd
